<a href="https://colab.research.google.com/github/vivekdevims/Python_Assignment/blob/main/Copy_of_Pandas_Practice_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Practice Notebook
Dear Students this notebook will help you practice Important Pandas operations step-by-step.

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
import pandas as pd
sale=pd.read_csv('/content/drive/MyDrive/data_set/sales.csv')

sale
stu=pd.read_csv('/content/drive/MyDrive/data_set/student_marks_unique.csv')

stu.to_json('/content/drive/MyDrive/data_set/student_1.json')

## 1. File Import using Pandas
Below are some examples to import files in Pandas and practice questions.

In [ ]:
# Example: Importing CSV, Excel, and JSON files
import pandas as pd

# Read CSV
df_csv = pd.read_csv('data.csv')

# Read Excel
df_excel = pd.read_excel('data.xlsx')

# Read JSON
df_json = pd.read_json('data.json')

### Practice Questions
1. Import the file `sales.csv` and display the first 5 rows.
2. Import the Excel file `students.xlsx` and check its columns.
3. Import any JSON file and find its shape.

In [37]:
print(sale.head(5))
a=("*")*40
a
########################
student=pd.read_excel('/content/drive/MyDrive/data_set/student.xlsx')
print(student.columns)
###########################
student_1=pd.read_json('/content/drive/MyDrive/data_set/student_1.json')
print(student_1.shape)
student.describe()

  emp_id emp_name sales_item  sale_value       city
0   E101    Priya      Mouse       77468  Bangalore
1   E102     Ravi     Laptop        7911    Lucknow
2   E103   Rajesh     Webcam       63754      Noida
3   E104    Priya    Monitor       42168  Hyderabad
4   E105     Ravi    Monitor        1499     Jaipur
Index(['Unnamed: 0', 'roll_no', 'name', 'english_marks', 'Math_marks',
       'Science_marks', 'Total', 'average', 'grade'],
      dtype='object')
(30, 8)

,Unnamed: 0,english_marks,Math_marks,Science_marks,Total,average
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,14.500000,71.233333,66.066667,67.333333,204.633333,68.211667
std,8.803408,18.779452,18.131575,16.274230,27.513612,9.170769
min,0.000000,44.000000,40.000000,41.000000,162.000000,54.000000
25%,7.250000,53.000000,51.500000,51.250000,185.000000,61.667500
50%,14.500000,72.000000,65.000000,65.000000,202.000000,67.335000
75%,21.750000,86.750000,78.750000,83.250000,218.500000,72.832500
max,29.000000,100.000000,99.000000,91.000000,266.000000,88.670000

## 2. File Export using Pandas
You can export data to different formats like CSV, Excel, and JSON.

In [ ]:
# Example: Exporting DataFrame to different formats
df.to_csv('output.csv', index=False)
df.to_excel('output.xlsx', index=False)
df.to_json('output.json')

### Practice Questions
1. Export any given DataFrame to CSV format without index.
2. Export the same DataFrame to Excel with the name 'Sheet1'.
3. Export to JSON format with indentation.

In [34]:

data = {
    "emp_id": ["E101", "E102", "E103"],
    "emp_name": ["Ankit", "Ravi", "Priya"],
    "sales_value": [25000, 40000, 32000]
}

df = pd.DataFrame(data)

# Export to CSV without index
df.to_csv("output1.csv", index=False)
df
df.to_excel("exported_sales.xlsx", sheet_name="Sheet1", index=False)
exported_sales = pd.read_excel("exported_sales.xlsx")
exported_sales

  emp_id emp_name  sales_value
0   E101    Ankit        25000
1   E102     Ravi        40000
2   E103    Priya        32000

## 3. Creating Series and DataFrames

In [ ]:
# Example: Creating Series and DataFrame
series = pd.Series([10, 20, 30], name='Sales')
data = {'Name': ['Amit', 'Riya', 'John'], 'Age': [22, 24, 26]}
df = pd.DataFrame(data)
print(series)
print(df)

### Practice Questions
1. Create a Series of 5 numbers named 'Marks'.
2. Create a DataFrame of 3 students with columns 'Name', 'Score', 'City'.
3. Print shape, head, and describe of your DataFrame.

In [36]:
s=pd.Series([10,20,30,40,50],name='Marks')
s
data = {'Name': ['Amit', 'Riya', 'John'], 'Score': [22, 24, 26],'city':['delhi','mumbai','pune']}
df = pd.DataFrame(data)
print(df.shape),print(df.head()),print(df.describe())

(3, 3)
   Name  Score    city
0  Amit     22   delhi
1  Riya     24  mumbai
2  John     26    pune
       Score
count    3.0
mean    24.0
std      2.0
min     22.0
25%     23.0
50%     24.0
75%     25.0
max     26.0

(None, None, None)

## 4. Indexing and Slicing in Pandas

In [ ]:
# Example: Indexing and Slicing
df['Name']
df[['Name', 'Age']]
df.iloc[0:2]
df.loc[df['Age'] > 22]

### Practice Questions
1. Select only the 'Score' column from your DataFrame.
2. Retrieve rows from index 1 to 3.
3. Filter rows where 'Age' > 23.

In [5]:
import pandas as pd
data = {'Name': ['Amit', 'Riya', 'John'], 'Score': [22, 24, 26],'city':['delhi','mumbai','pune']}
df = pd.DataFrame(data)
print(df.iloc[:,1])
print(df.iloc[1:4])
print(df[df['Score']>23])

0    22
1    24
2    26
Name: Score, dtype: int64
   Name  Score    city
1  Riya     24  mumbai
2  John     26    pune
   Name  Score    city
1  Riya     24  mumbai
2  John     26    pune

## 5. Merging and Concatenation

In [ ]:
# Example: Merge and Concat
df1 = pd.DataFrame({'ID': [1,2], 'Name': ['A', 'B']})
df2 = pd.DataFrame({'ID': [1,2], 'Score': [85, 90]})
merged = pd.merge(df1, df2, on='ID')
print(merged)

# Concat
df3 = pd.concat([df1, df2], axis=0, ignore_index=True)

### Practice Questions
1. Merge two DataFrames 'students' and 'marks' on 'ID'.
2. Perform left join between two given DataFrames.
3. Concatenate two DataFrames vertically and reset the index.

In [7]:
data1=pd.DataFrame({'id':[1,2,3], 'name': ["abhi", "ravi", "priya"]})
data2=pd.DataFrame({'id':[1,2,3], 'score': [22, 24, 26]})
merged = pd.merge(data1, data2, on='id')
print(merged)

con=pd.concat([data1,data2],axis=0,ignore_index=True)
con

   id   name  score
0   1   abhi     22
1   2   ravi     24
2   3  priya     26

   id   name  score
0   1   abhi    NaN
1   2   ravi    NaN
2   3  priya    NaN
3   1    NaN   22.0
4   2    NaN   24.0
5   3    NaN   26.0

## 6. Pivot Tables and GroupBy

In [ ]:
# Example: Pivot and GroupBy
df = pd.DataFrame({'Region': ['North', 'South', 'North'], 'Month': ['Jan', 'Jan', 'Feb'], 'Sales': [250, 300, 400]})

pivot = df.pivot_table(values='Sales', index='Region', columns='Month', aggfunc='sum', fill_value=0)
grouped = df.groupby('Region')['Sales'].sum()
print(pivot)
print(grouped)

### Practice Questions
1. Group the DataFrame by 'Month' and find total sales.
2. Create a pivot table to show Region-wise total sales.
3. Group data by 'Region' and count number of entries.

In [17]:
sale1=pd.DataFrame({'location': ['delhi','goa',"u.p",'haryana','tamil_nadu',"kerala"], 'month':['jan','feb','mar','apr','may','jun'],'sales': [1000,2000,3000,000,4000,5000]})
pivot=sale1.pivot_table(  values='sales',index='location',columns='month',aggfunc='sum',fill_value=0)
print(pivot)
grouped=sale1.groupby('location')['sales'].sum()
print(grouped)

month       apr   feb   jan   jun   mar   may
location
delhi         0     0  1000     0     0     0
goa           0  2000     0     0     0     0
haryana       0     0     0     0     0     0
kerala        0     0     0  5000     0     0
tamil_nadu    0     0     0     0     0  4000
u.p           0     0     0     0  3000     0
location
delhi         1000
goa           2000
haryana          0
kerala        5000
tamil_nadu    4000
u.p           3000
Name: sales, dtype: int64

## Optional Practice (Medium Level)
These questions test your overall understanding of Pandas.

1. Import a dataset and clean all missing values, rename columns properly, and export it back to Excel.

Dataset- https://drive.google.com/file/d/1kw_Sdib3WCo_acQYA851poCUdKcWgfYs/view?usp=sharing

In [38]:
messy=pd.read_csv('/content/drive/MyDrive/data_set/messy.csv')
print(messy,end="")
messy.dropna(inplace=True)
messy
print()
print("*"*30)
m=messy.rename(columns={"city":"location"})
print(m)
messy.to_excel('/content/drive/MyDrive/data_set/messy.xlsx')

     Name   Age(Years)    City  Sales( Rs)
0     Amit        25.0   Delhi      2500.0
1   Priya          NaN  Mumbai      3000.0
2      NaN        30.0   Delhi         NaN
3    Rohan        22.0     NaN      2000.0
4     Neha        28.0    Pune      4000.0
5      NaN        30.0   Delhi         NaN
******************************
     Name   Age(Years)   City  Sales( Rs)
0     Amit        25.0  Delhi      2500.0
4     Neha        28.0   Pune      4000.0

2. Combine multiple CSV files from a folder into one DataFrame and find top 5 entries by a numeric column like 'Sales'.

Dataset- https://drive.google.com/drive/folders/1zgJs_6r8Aa_-93YXmYXfxOK5L4hVUI9Q?usp=sharing

In [ ]:
# Answer here